# Generated by Django 5.1.2 on 2024-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ManyToManyField(to='first1site.authors'),
        ),
    ]
