# Generated by Django 5.1.2 on 2024-12-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0002_remove_books_author_id_books_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first1site.authors'),
        ),
    ]
