# Generated by Django 5.1.2 on 2024-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0004_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='users_file/'),
        ),
    ]
