# Generated by Django 5.1.2 on 2024-12-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0005_alter_userfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
