# Generated by Django 5.1.2 on 2024-12-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0006_rename_user_id_userfile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user',
            new_name='user_id',
        ),
    ]
