# Generated by Django 5.1.2 on 2025-01-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first1site', '0007_rename_user_userfile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
